/* Shared data for the squad PR dashboard directions.
   GENERATED by fetch-data.mjs from real WooCommerce PRs — do not hand-edit.
   Re-run:  GH_TOKEN=$(gh auth token) node fetch-data.mjs */

(function () {
	const SQUAD = [
	{
		"id": "j",
		"name": "Jill",
		"handle": "j111q",
		"avatar": "https://avatars.githubusercontent.com/u/65582817?v=4",
		"color": "#7F54B3",
		"fg": "#fff"
	},
	{
		"id": "ann",
		"name": "Ann",
		"handle": "annchichi",
		"avatar": "https://avatars.githubusercontent.com/u/13378873?v=4",
		"color": "#3C2A7D",
		"fg": "#fff"
	},
	{
		"id": "poli",
		"name": "Poli",
		"handle": "poligilad-auto",
		"avatar": "https://avatars.githubusercontent.com/u/83961704?v=4",
		"color": "#533582",
		"fg": "#fff"
	},
	{
		"id": "jana",
		"name": "Jana",
		"handle": "JanaMW27",
		"avatar": "https://avatars.githubusercontent.com/u/71137829?v=4",
		"color": "#C9B8E8",
		"fg": "#1E1142"
	},
	{
		"id": "vero",
		"name": "Veronica",
		"handle": "verofasulo",
		"avatar": "https://avatars.githubusercontent.com/u/98944206?v=4",
		"color": "#E84A9C",
		"fg": "#fff"
	}
];

	const REPOS = [
	"woocommerce/woocommerce",
	"Automattic/woocommerce-payments",
	"mailpoet/mailpoet",
	"woocommerce/woocommerce-shipping",
	"woocommerce/google-listings-and-ads"
];

	const MERGED = [
	{
		"title": "Fix: Improve color contrast for attribute placeholder text (WCAG 2.2 AA)",
		"repo": "woocommerce/woocommerce",
		"number": 65608,
		"url": "https://github.com/woocommerce/woocommerce/pull/65608",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1781268194000,
		"fresh": false
	},
	{
		"title": "Fix product ID row action contrast",
		"repo": "woocommerce/woocommerce",
		"number": 65667,
		"url": "https://github.com/woocommerce/woocommerce/pull/65667",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1781261256000,
		"fresh": false
	},
	{
		"title": "Fix metabox delete link contrast",
		"repo": "woocommerce/woocommerce",
		"number": 65605,
		"url": "https://github.com/woocommerce/woocommerce/pull/65605",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1781261125000,
		"fresh": false
	},
	{
		"title": "Refresh legacy admin empty states",
		"repo": "woocommerce/woocommerce",
		"number": 64645,
		"url": "https://github.com/woocommerce/woocommerce/pull/64645",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1781173544000,
		"fresh": false
	},
	{
		"title": "Analytics: align Date range and Data status, refine Update now button",
		"repo": "woocommerce/woocommerce",
		"number": 64846,
		"url": "https://github.com/woocommerce/woocommerce/pull/64846",
		"area": "Analytics",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1781082492000,
		"fresh": false
	},
	{
		"title": "Make WooPay save-info copy smaller",
		"repo": "Automattic/woocommerce-payments",
		"number": 11734,
		"url": "https://github.com/Automattic/woocommerce-payments/pull/11734",
		"area": "Payments",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1780059781000,
		"fresh": false
	},
	{
		"title": "Remove the task list reminder bar from Woo admin",
		"repo": "woocommerce/woocommerce",
		"number": 64353,
		"url": "https://github.com/woocommerce/woocommerce/pull/64353",
		"area": "Onboarding",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1779462593000,
		"fresh": false
	},
	{
		"title": "Add variation-specific edit panel to new variation experience",
		"repo": "woocommerce/woocommerce",
		"number": 65256,
		"url": "https://github.com/woocommerce/woocommerce/pull/65256",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1779457232000,
		"fresh": false
	},
	{
		"title": "Fix variation quick edit crashes and save errors in experimental products app",
		"repo": "woocommerce/woocommerce",
		"number": 65159,
		"url": "https://github.com/woocommerce/woocommerce/pull/65159",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1779438687000,
		"fresh": false
	},
	{
		"title": "Replace Upsells with Grouped products in grouped product edit form",
		"repo": "woocommerce/woocommerce",
		"number": 65173,
		"url": "https://github.com/woocommerce/woocommerce/pull/65173",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779286460000,
		"fresh": false
	},
	{
		"title": "Tailor variation row actions in the experimental products app",
		"repo": "woocommerce/woocommerce",
		"number": 65199,
		"url": "https://github.com/woocommerce/woocommerce/pull/65199",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779281478000,
		"fresh": false
	},
	{
		"title": "Drop wrapping quotes around the product name in the delete confirmation modal",
		"repo": "woocommerce/woocommerce",
		"number": 65197,
		"url": "https://github.com/woocommerce/woocommerce/pull/65197",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779281344000,
		"fresh": false
	},
	{
		"title": "Match the products app drawer title to the design-system Drawer header (20px)",
		"repo": "woocommerce/woocommerce",
		"number": 65198,
		"url": "https://github.com/woocommerce/woocommerce/pull/65198",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779281131000,
		"fresh": false
	},
	{
		"title": "Bump the product edit drawer header horizontal padding to 24px",
		"repo": "woocommerce/woocommerce",
		"number": 65160,
		"url": "https://github.com/woocommerce/woocommerce/pull/65160",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779278809000,
		"fresh": false
	},
	{
		"title": "Add Restore and Permanently delete actions to trashed products",
		"repo": "woocommerce/woocommerce",
		"number": 65008,
		"url": "https://github.com/woocommerce/woocommerce/pull/65008",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779278632000,
		"fresh": false
	},
	{
		"title": "Add Beta feedback badge next to the Products page title",
		"repo": "woocommerce/woocommerce",
		"number": 65163,
		"url": "https://github.com/woocommerce/woocommerce/pull/65163",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779273636000,
		"fresh": false
	},
	{
		"title": "internal-style-build: alias WordPress-defaults SCSS vars to @wordpress/base-styles",
		"repo": "woocommerce/woocommerce",
		"number": 65157,
		"url": "https://github.com/woocommerce/woocommerce/pull/65157",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1779243098000,
		"fresh": false
	},
	{
		"title": "Switch boolean fields to checkboxes in the products app",
		"repo": "woocommerce/woocommerce",
		"number": 65000,
		"url": "https://github.com/woocommerce/woocommerce/pull/65000",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1779190735000,
		"fresh": false
	},
	{
		"title": "Reorder Product Data tabs when variations classic redesign is on",
		"repo": "woocommerce/woocommerce",
		"number": 65108,
		"url": "https://github.com/woocommerce/woocommerce/pull/65108",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1779185898000,
		"fresh": false
	},
	{
		"title": "Floating header: polish + WP design token alignment",
		"repo": "woocommerce/woocommerce",
		"number": 64885,
		"url": "https://github.com/woocommerce/woocommerce/pull/64885",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1779171846000,
		"fresh": false
	},
	{
		"title": "Improve payment setup fallback coverage",
		"repo": "woocommerce/woocommerce",
		"number": 64860,
		"url": "https://github.com/woocommerce/woocommerce/pull/64860",
		"area": "Payments",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1779164511000,
		"fresh": false
	},
	{
		"title": "Align embedded admin notice padding",
		"repo": "woocommerce/woocommerce",
		"number": 64809,
		"url": "https://github.com/woocommerce/woocommerce/pull/64809",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1779164091000,
		"fresh": false
	},
	{
		"title": "Floating header: Tracks instrumentation for Screen Options and Help icon clicks",
		"repo": "woocommerce/woocommerce",
		"number": 65131,
		"url": "https://github.com/woocommerce/woocommerce/pull/65131",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1779157310000,
		"fresh": false
	},
	{
		"title": "Polish shipping fields in the product edit drawer",
		"repo": "woocommerce/woocommerce",
		"number": 65127,
		"url": "https://github.com/woocommerce/woocommerce/pull/65127",
		"area": "Shipping",
		"flagged": true,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"ts": 1779122893000,
		"fresh": false
	},
	{
		"title": "Align Images field label spacing in experimental products app",
		"repo": "woocommerce/woocommerce",
		"number": 64993,
		"url": "https://github.com/woocommerce/woocommerce/pull/64993",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778837391000,
		"fresh": false
	},
	{
		"title": "Remove the 'On sale' toggle and always show the sale price field",
		"repo": "woocommerce/woocommerce",
		"number": 64995,
		"url": "https://github.com/woocommerce/woocommerce/pull/64995",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778837203000,
		"fresh": false
	},
	{
		"title": "Update product editor field labels for clarity",
		"repo": "woocommerce/woocommerce",
		"number": 64992,
		"url": "https://github.com/woocommerce/woocommerce/pull/64992",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778836778000,
		"fresh": false
	},
	{
		"title": "Add Product type column to the experimental products app",
		"repo": "woocommerce/woocommerce",
		"number": 64907,
		"url": "https://github.com/woocommerce/woocommerce/pull/64907",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778781879000,
		"fresh": false
	},
	{
		"title": "Add per-tab empty states to the experimental products app",
		"repo": "woocommerce/woocommerce",
		"number": 64913,
		"url": "https://github.com/woocommerce/woocommerce/pull/64913",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778773017000,
		"fresh": false
	},
	{
		"title": "Fix quick edit drawer title size and header spacing",
		"repo": "woocommerce/woocommerce",
		"number": 64811,
		"url": "https://github.com/woocommerce/woocommerce/pull/64811",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778764764000,
		"fresh": false
	},
	{
		"title": "Remove the underline from product title links",
		"repo": "woocommerce/woocommerce",
		"number": 64741,
		"url": "https://github.com/woocommerce/woocommerce/pull/64741",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778763809000,
		"fresh": false
	},
	{
		"title": "Render dimension fields side-by-side in the quick edit panel",
		"repo": "woocommerce/woocommerce",
		"number": 64785,
		"url": "https://github.com/woocommerce/woocommerce/pull/64785",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778754812000,
		"fresh": false
	},
	{
		"title": "Add Stock quantity filter to the experimental products app product list",
		"repo": "woocommerce/woocommerce",
		"number": 64827,
		"url": "https://github.com/woocommerce/woocommerce/pull/64827",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778754746000,
		"fresh": false
	},
	{
		"title": "Add Shipping Class filter to the experimental products app product list",
		"repo": "woocommerce/woocommerce",
		"number": 64823,
		"url": "https://github.com/woocommerce/woocommerce/pull/64823",
		"area": "Shipping",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778745693000,
		"fresh": false
	},
	{
		"title": "Animate the quick edit drawer close transition and close on save",
		"repo": "woocommerce/woocommerce",
		"number": 64858,
		"url": "https://github.com/woocommerce/woocommerce/pull/64858",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778745597000,
		"fresh": false
	},
	{
		"title": "Floating header: suppress duplicate H1, unify chrome to icon tabs",
		"repo": "woocommerce/woocommerce",
		"number": 64643,
		"url": "https://github.com/woocommerce/woocommerce/pull/64643",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1778731997000,
		"fresh": false
	},
	{
		"title": "Redesign the experimental products app header",
		"repo": "woocommerce/woocommerce",
		"number": 64851,
		"url": "https://github.com/woocommerce/woocommerce/pull/64851",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778709845000,
		"fresh": false
	},
	{
		"title": "Use the @wordpress/ui Select primitive for quick edit selects",
		"repo": "woocommerce/woocommerce",
		"number": 64784,
		"url": "https://github.com/woocommerce/woocommerce/pull/64784",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778709638000,
		"fresh": false
	},
	{
		"title": "Add Tags filter to the experimental products app product list",
		"repo": "woocommerce/woocommerce",
		"number": 64822,
		"url": "https://github.com/woocommerce/woocommerce/pull/64822",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778687160000,
		"fresh": false
	},
	{
		"title": "Remove helper text from Featured product toggle in quick edit panel",
		"repo": "woocommerce/woocommerce",
		"number": 64814,
		"url": "https://github.com/woocommerce/woocommerce/pull/64814",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778663235000,
		"fresh": false
	},
	{
		"title": "Remove helper text from Tags field in quick edit panel",
		"repo": "woocommerce/woocommerce",
		"number": 64816,
		"url": "https://github.com/woocommerce/woocommerce/pull/64816",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778662788000,
		"fresh": false
	},
	{
		"title": "Rename Categories filter and column to Category",
		"repo": "woocommerce/woocommerce",
		"number": 64821,
		"url": "https://github.com/woocommerce/woocommerce/pull/64821",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778662707000,
		"fresh": false
	},
	{
		"title": "Add Brands filter to the experimental products app product list",
		"repo": "woocommerce/woocommerce",
		"number": 64826,
		"url": "https://github.com/woocommerce/woocommerce/pull/64826",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778661897000,
		"fresh": false
	},
	{
		"title": "Improve payment provider setup error message",
		"repo": "woocommerce/woocommerce",
		"number": 64799,
		"url": "https://github.com/woocommerce/woocommerce/pull/64799",
		"area": "Payments",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778654148000,
		"fresh": false
	},
	{
		"title": "Add order-detail-redesign feature flag and 1200px cap on Order edit",
		"repo": "woocommerce/woocommerce",
		"number": 64669,
		"url": "https://github.com/woocommerce/woocommerce/pull/64669",
		"area": "Orders",
		"flagged": true,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"ts": 1778589542000,
		"fresh": false
	},
	{
		"title": "Fix Marketplace product card title focus ring",
		"repo": "woocommerce/woocommerce",
		"number": 64788,
		"url": "https://github.com/woocommerce/woocommerce/pull/64788",
		"area": "Marketplace",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778575263000,
		"fresh": false
	},
	{
		"title": "Add email template canvas affordance",
		"repo": "woocommerce/woocommerce",
		"number": 64703,
		"url": "https://github.com/woocommerce/woocommerce/pull/64703",
		"area": "Emails",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778572405000,
		"fresh": false
	},
	{
		"title": "Align admin destructive action red with WordPress 7.0 error red",
		"repo": "woocommerce/woocommerce",
		"number": 64203,
		"url": "https://github.com/woocommerce/woocommerce/pull/64203",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778569389000,
		"fresh": false
	},
	{
		"title": "Align shipping destructive action red with WordPress 7.0 error red",
		"repo": "woocommerce/woocommerce",
		"number": 64204,
		"url": "https://github.com/woocommerce/woocommerce/pull/64204",
		"area": "Shipping",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778569360000,
		"fresh": false
	},
	{
		"title": "Fix Marketplace header account button height and alignment",
		"repo": "woocommerce/woocommerce",
		"number": 64420,
		"url": "https://github.com/woocommerce/woocommerce/pull/64420",
		"area": "Marketplace",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778568958000,
		"fresh": false
	},
	{
		"title": "Improve images field: label, drag-and-drop, uniform thumbnails",
		"repo": "woocommerce/woocommerce",
		"number": 64715,
		"url": "https://github.com/woocommerce/woocommerce/pull/64715",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778501772000,
		"fresh": false
	},
	{
		"title": "Add Tags, Brands, Date, and GTIN columns to the products list",
		"repo": "woocommerce/woocommerce",
		"number": 64713,
		"url": "https://github.com/woocommerce/woocommerce/pull/64713",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778495818000,
		"fresh": false
	},
	{
		"title": "Order notes meta box: clarify visibility, modernize bubble styling",
		"repo": "woocommerce/woocommerce",
		"number": 64476,
		"url": "https://github.com/woocommerce/woocommerce/pull/64476",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1778477831000,
		"fresh": false
	},
	{
		"title": "Hide WordPress admin footer on the products dashboard",
		"repo": "woocommerce/woocommerce",
		"number": 64705,
		"url": "https://github.com/woocommerce/woocommerce/pull/64705",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778244040000,
		"fresh": false
	},
	{
		"title": "Add Quick edit to the products list bulk-action bar",
		"repo": "woocommerce/woocommerce",
		"number": 64704,
		"url": "https://github.com/woocommerce/woocommerce/pull/64704",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778242076000,
		"fresh": false
	},
	{
		"title": "Add Quick edit as a primary row action in the products list",
		"repo": "woocommerce/woocommerce",
		"number": 64702,
		"url": "https://github.com/woocommerce/woocommerce/pull/64702",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778241024000,
		"fresh": false
	},
	{
		"title": "Align product status options across select, tabs, and badge",
		"repo": "woocommerce/woocommerce",
		"number": 64707,
		"url": "https://github.com/woocommerce/woocommerce/pull/64707",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778236124000,
		"fresh": false
	},
	{
		"title": "Render the Stock column as a Badge",
		"repo": "woocommerce/woocommerce",
		"number": 64706,
		"url": "https://github.com/woocommerce/woocommerce/pull/64706",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778235334000,
		"fresh": false
	},
	{
		"title": "Remove the SKU field helper text",
		"repo": "woocommerce/woocommerce",
		"number": 64709,
		"url": "https://github.com/woocommerce/woocommerce/pull/64709",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778230688000,
		"fresh": false
	},
	{
		"title": "Remove the Product type field from the quick edit panel",
		"repo": "woocommerce/woocommerce",
		"number": 64714,
		"url": "https://github.com/woocommerce/woocommerce/pull/64714",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778230645000,
		"fresh": false
	},
	{
		"title": "Remove the Categories field helper text",
		"repo": "woocommerce/woocommerce",
		"number": 64710,
		"url": "https://github.com/woocommerce/woocommerce/pull/64710",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1778230579000,
		"fresh": false
	},
	{
		"title": "Use --wp-admin-border-width-focus for focus ring widths",
		"repo": "woocommerce/woocommerce",
		"number": 64249,
		"url": "https://github.com/woocommerce/woocommerce/pull/64249",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778090563000,
		"fresh": false
	},
	{
		"title": "Align Woo admin gray text colors with WordPress 7.0 (via SCSS tokens)",
		"repo": "woocommerce/woocommerce",
		"number": 64280,
		"url": "https://github.com/woocommerce/woocommerce/pull/64280",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1778087398000,
		"fresh": false
	},
	{
		"title": "Add categories as default column in All Products list",
		"repo": "woocommerce/woocommerce",
		"number": 64496,
		"url": "https://github.com/woocommerce/woocommerce/pull/64496",
		"area": "Products & catalog",
		"flagged": true,
		"authors": [
			"vero"
		],
		"reviewers": [],
		"ts": 1777882855000,
		"fresh": false
	},
	{
		"title": "Fix widows in admin body copy not covered by the global rule",
		"repo": "woocommerce/woocommerce",
		"number": 64453,
		"url": "https://github.com/woocommerce/woocommerce/pull/64453",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777872173000,
		"fresh": false
	},
	{
		"title": "Align order preview action buttons with WordPress 7.0 secondary style",
		"repo": "woocommerce/woocommerce",
		"number": 64354,
		"url": "https://github.com/woocommerce/woocommerce/pull/64354",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777635274000,
		"fresh": false
	},
	{
		"title": "Fix: replace developer-facing plugin install error with merchant-friendly copy",
		"repo": "woocommerce/woocommerce",
		"number": 64186,
		"url": "https://github.com/woocommerce/woocommerce/pull/64186",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777479023000,
		"fresh": false
	},
	{
		"title": "Link meta box radius bridge to upstream Trac ticket #65142",
		"repo": "woocommerce/woocommerce",
		"number": 64454,
		"url": "https://github.com/woocommerce/woocommerce/pull/64454",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777475416000,
		"fresh": false
	},
	{
		"title": "Stop rendering inbox note images and deprecate the API",
		"repo": "woocommerce/woocommerce",
		"number": 64443,
		"url": "https://github.com/woocommerce/woocommerce/pull/64443",
		"area": "Home",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777432301000,
		"fresh": false
	},
	{
		"title": "Align legacy admin success notice with WordPress 7.0 palette",
		"repo": "woocommerce/woocommerce",
		"number": 64212,
		"url": "https://github.com/woocommerce/woocommerce/pull/64212",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777404578000,
		"fresh": false
	},
	{
		"title": "Align settings notice with WordPress 7.0 palette",
		"repo": "woocommerce/woocommerce",
		"number": 64237,
		"url": "https://github.com/woocommerce/woocommerce/pull/64237",
		"area": "Settings",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777404470000,
		"fresh": false
	},
	{
		"title": "Use --wp-admin-theme-color for legacy Select2",
		"repo": "woocommerce/woocommerce",
		"number": 64244,
		"url": "https://github.com/woocommerce/woocommerce/pull/64244",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777404446000,
		"fresh": false
	},
	{
		"title": "Fix confusing error notice in shipping tour close handler",
		"repo": "woocommerce/woocommerce",
		"number": 64181,
		"url": "https://github.com/woocommerce/woocommerce/pull/64181",
		"area": "Shipping",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777403417000,
		"fresh": false
	},
	{
		"title": "Align Product / Coupon Data panel labels and help-tips with 40px inputs (WP 7.0)",
		"repo": "woocommerce/woocommerce",
		"number": 64327,
		"url": "https://github.com/woocommerce/woocommerce/pull/64327",
		"area": "Coupons",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777393186000,
		"fresh": false
	},
	{
		"title": "Align order edit page address Select2 with WordPress 7.0 input height",
		"repo": "woocommerce/woocommerce",
		"number": 64389,
		"url": "https://github.com/woocommerce/woocommerce/pull/64389",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777375393000,
		"fresh": false
	},
	{
		"title": "Fix: adopt $radius-s (2px) border-radius for Woo custom inputs and buttons (WP 7.0)",
		"repo": "woocommerce/woocommerce",
		"number": 64417,
		"url": "https://github.com/woocommerce/woocommerce/pull/64417",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777372575000,
		"fresh": false
	},
	{
		"title": "Tokenize hardcoded grays in Woo admin for WP 7.0 alignment",
		"repo": "woocommerce/woocommerce",
		"number": 64276,
		"url": "https://github.com/woocommerce/woocommerce/pull/64276",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777368221000,
		"fresh": false
	},
	{
		"title": "Show merchant-friendly message on plugin install upgrader failure",
		"repo": "woocommerce/woocommerce",
		"number": 64397,
		"url": "https://github.com/woocommerce/woocommerce/pull/64397",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777367422000,
		"fresh": false
	},
	{
		"title": "Align Woo legacy admin custom button border-radius with WordPress 7.0",
		"repo": "woocommerce/woocommerce",
		"number": 64262,
		"url": "https://github.com/woocommerce/woocommerce/pull/64262",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777366698000,
		"fresh": false
	},
	{
		"title": "Adopt WP 7.0 form-control sizing on settings inputs and Select2 multi-select",
		"repo": "woocommerce/woocommerce",
		"number": 64322,
		"url": "https://github.com/woocommerce/woocommerce/pull/64322",
		"area": "Settings",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1777365604000,
		"fresh": false
	},
	{
		"title": "Align structural admin elements with WP theme color CSS custom properties",
		"repo": "woocommerce/woocommerce",
		"number": 64196,
		"url": "https://github.com/woocommerce/woocommerce/pull/64196",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777345927000,
		"fresh": false
	},
	{
		"title": "Add 8px border-radius to WooCommerce editor meta boxes (WP 7.0 alignment)",
		"repo": "woocommerce/woocommerce",
		"number": 64191,
		"url": "https://github.com/woocommerce/woocommerce/pull/64191",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777289336000,
		"fresh": false
	},
	{
		"title": "Drop default icon from CES feedback snackbars",
		"repo": "woocommerce/woocommerce",
		"number": 64357,
		"url": "https://github.com/woocommerce/woocommerce/pull/64357",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777268611000,
		"fresh": false
	},
	{
		"title": "Copy improvement: clear permission error when user cannot install plugins",
		"repo": "woocommerce/woocommerce",
		"number": 64187,
		"url": "https://github.com/woocommerce/woocommerce/pull/64187",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1777023317000,
		"fresh": false
	},
	{
		"title": "Add offline awareness to WooCommerce admin (reuses WP core #lost-connection-notice)",
		"repo": "woocommerce/woocommerce",
		"number": 64334,
		"url": "https://github.com/woocommerce/woocommerce/pull/64334",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"ts": 1776928898000,
		"fresh": false
	},
	{
		"title": "Map email test-send errors to merchant-friendly copy",
		"repo": "woocommerce/woocommerce",
		"number": 64286,
		"url": "https://github.com/woocommerce/woocommerce/pull/64286",
		"area": "Emails",
		"flagged": false,
		"authors": [
			"ann"
		],
		"reviewers": [],
		"ts": 1776856572000,
		"fresh": false
	}
];

	const OPEN = [
	{
		"title": "Update product publish panel controls",
		"repo": "woocommerce/woocommerce",
		"number": 65794,
		"url": "https://github.com/woocommerce/woocommerce/pull/65794",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781708435000
	},
	{
		"title": "Update product status filter availability labels",
		"repo": "woocommerce/woocommerce",
		"number": 65803,
		"url": "https://github.com/woocommerce/woocommerce/pull/65803",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1781700045000
	},
	{
		"title": "Improve product editor permalink layout",
		"repo": "woocommerce/woocommerce",
		"number": 65640,
		"url": "https://github.com/woocommerce/woocommerce/pull/65640",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781688714000
	},
	{
		"title": "Coupon edit: apply 2-column grid sizing standard (720 / 24 / 320)",
		"repo": "woocommerce/woocommerce",
		"number": 65717,
		"url": "https://github.com/woocommerce/woocommerce/pull/65717",
		"area": "Coupons",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1781687094000
	},
	{
		"title": "Improve summary trend indicator contrast",
		"repo": "woocommerce/woocommerce",
		"number": 65784,
		"url": "https://github.com/woocommerce/woocommerce/pull/65784",
		"area": "Other admin",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781684335000
	},
	{
		"title": "Align Order Edit meta boxes with WordPress 7.0 design conventions",
		"repo": "woocommerce/woocommerce",
		"number": 64564,
		"url": "https://github.com/woocommerce/woocommerce/pull/64564",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781627493000
	},
	{
		"title": "Migrate customer stock notification screens to the order actions \"more actions\" menu",
		"repo": "woocommerce/woocommerce",
		"number": 65788,
		"url": "https://github.com/woocommerce/woocommerce/pull/65788",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"j"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1781626536000
	},
	{
		"title": "Fix order edit screen text color contrast for WCAG AA",
		"repo": "woocommerce/woocommerce",
		"number": 65714,
		"url": "https://github.com/woocommerce/woocommerce/pull/65714",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1781604154000
	},
	{
		"title": "Improve legacy WooCommerce dashboard widgets",
		"repo": "woocommerce/woocommerce",
		"number": 65704,
		"url": "https://github.com/woocommerce/woocommerce/pull/65704",
		"area": "Home",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781596269000
	},
	{
		"title": "Hide downloads metabox on orders without downloadable items",
		"repo": "woocommerce/woocommerce",
		"number": 65205,
		"url": "https://github.com/woocommerce/woocommerce/pull/65205",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781279537000
	},
	{
		"title": "Order detail: apply 2-column grid sizing standard (720 / 24 / 320)",
		"repo": "woocommerce/woocommerce",
		"number": 65699,
		"url": "https://github.com/woocommerce/woocommerce/pull/65699",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781269696000
	},
	{
		"title": "Add prev/next order navigation to Order detail page header",
		"repo": "woocommerce/woocommerce",
		"number": 64711,
		"url": "https://github.com/woocommerce/woocommerce/pull/64711",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1781186434000
	},
	{
		"title": "[DO NOT MERGE] Product editor design prototype with dev panel",
		"repo": "woocommerce/woocommerce",
		"number": 65482,
		"url": "https://github.com/woocommerce/woocommerce/pull/65482",
		"area": "Products & catalog",
		"flagged": false,
		"authors": [
			"poli"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1781097752000
	},
	{
		"title": "[Prototype, do not merge] Order detail Update redesign — visual demo",
		"repo": "woocommerce/woocommerce",
		"number": 65176,
		"url": "https://github.com/woocommerce/woocommerce/pull/65176",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Open",
		"ts": 1779916658000
	},
	{
		"title": "[DEMO, do not merge] Order detail page polish, all four PRs stacked",
		"repo": "woocommerce/woocommerce",
		"number": 65142,
		"url": "https://github.com/woocommerce/woocommerce/pull/65142",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1779176538000
	},
	{
		"title": "[Sandbox] Order edit page UI explorations (not for review/merge)",
		"repo": "woocommerce/woocommerce",
		"number": 64626,
		"url": "https://github.com/woocommerce/woocommerce/pull/64626",
		"area": "Orders",
		"flagged": false,
		"authors": [
			"jana"
		],
		"reviewers": [],
		"status": "Draft",
		"ts": 1778012568000
	}
];

	const AREAS = [
	{
		"name": "Products & catalog",
		"count": 40
	},
	{
		"name": "Other admin",
		"count": 25
	},
	{
		"name": "Orders",
		"count": 4
	},
	{
		"name": "Shipping",
		"count": 4
	},
	{
		"name": "Payments",
		"count": 3
	},
	{
		"name": "Emails",
		"count": 2
	},
	{
		"name": "Marketplace",
		"count": 2
	},
	{
		"name": "Settings",
		"count": 2
	},
	{
		"name": "Analytics",
		"count": 1
	},
	{
		"name": "Coupons",
		"count": 1
	},
	{
		"name": "Home",
		"count": 1
	},
	{
		"name": "Onboarding",
		"count": 1
	}
];

	const TOTALS = {
	"merged": 86,
	"surfaces": 12,
	"repos": 2,
	"since": "April 2026",
	"mergedFlagged": 42,
	"mergedPublic": 44
};

	const DATA_META = {
	"updatedAt": "2026-06-17T20:08:36.605Z"
};

	function person(id) {
		return SQUAD.find(function (p) { return p.id === id; });
	}

	/* Relative time, computed at render so it's always live (no baked strings). */
	function whenLabel(ts) {
		const h = Math.max(0, Math.round((Date.now() - ts) / 36e5));
		if (h < 1) return "just now";
		if (h < 24) return h + "h ago";
		const d = Math.round(h / 24);
		if (d < 7) return d + "d ago";
		const w = Math.round(d / 7);
		if (w < 5) return w + "w ago";
		return Math.round(d / 30) + "mo ago";
	}
	/* Open/draft PRs read "updated …"; merged PRs just show the time. */
	function prWhen(pr) {
		return (pr.status && pr.status !== "Merged" ? "updated " : "") + whenLabel(pr.ts);
	}

	function pluralAge(n, unit) {
		return n + " " + unit + (n === 1 ? "" : "s") + " ago";
	}

	function dataAgeLabel(ts) {
		const seconds = Math.max(0, Math.round((Date.now() - ts) / 1000));
		if (seconds < 45) return "just now";
		const minutes = Math.round(seconds / 60);
		if (minutes < 60) return pluralAge(minutes, "minute");
		const hours = Math.round(minutes / 60);
		if (hours < 24) return pluralAge(hours, "hour");
		const days = Math.round(hours / 24);
		if (days < 30) return pluralAge(days, "day");
		const months = Math.round(days / 30);
		if (months < 12) return pluralAge(months, "month");
		return pluralAge(Math.round(days / 365), "year");
	}

	function dataUpdatedLabel() {
		const ts = new Date(DATA_META.updatedAt).getTime();
		if (Number.isNaN(ts)) return "Last updated recently";
		return "Last updated " + dataAgeLabel(ts);
	}

	/* Easter egg: rainbow sprinkle burst on merged-badge click */
	const SPRINKLE_COLORS = ["#FF3B30", "#FF9500", "#FFD60A", "#34C759", "#2F6BFF", "#5E5CE6", "#7F54B3", "#E84A9C", "#32ADE6"];
	function sprinkleBurst(e) {
		const x = e.clientX, y = e.clientY;
		for (let i = 0; i < 44; i++) {
			const s = document.createElement("div");
			const angle = Math.random() * Math.PI * 2;
			const dist = 70 + Math.random() * 180;
			const dx = Math.cos(angle) * dist;
			const dy = Math.sin(angle) * dist - 40;
			const w = 3 + Math.random() * 2.5;
			s.style.cssText =
				"position:fixed;left:" + x + "px;top:" + y + "px;width:" + w + "px;height:" + (6 + Math.random() * 5) +
				"px;border-radius:2px;pointer-events:none;z-index:99999;background:" +
				SPRINKLE_COLORS[Math.floor(Math.random() * SPRINKLE_COLORS.length)] +
				";transform:rotate(" + Math.random() * 360 + "deg);transition:transform 1s cubic-bezier(0.2,0.8,0.2,1),opacity 1s ease-out;";
			document.body.appendChild(s);
			requestAnimationFrame(function () {
				requestAnimationFrame(function () {
					s.style.transform = "translate(" + dx + "px," + (dy + 110) + "px) rotate(" + (Math.random() * 720 - 360) + "deg)";
					s.style.opacity = "0";
				});
			});
			setTimeout(function () { s.remove(); }, 1100);
		}
	}

	window.DASH = { SQUAD: SQUAD, REPOS: REPOS, MERGED: MERGED, OPEN: OPEN, AREAS: AREAS, TOTALS: TOTALS, DATA_META: DATA_META, person: person, whenLabel: whenLabel, prWhen: prWhen, dataUpdatedLabel: dataUpdatedLabel, sprinkleBurst: sprinkleBurst };
})();
